display:
  borderless-fullscreen: false
  resolution:
    width: 1080
    height: 768
debug:
  world-name: small.tmx
  limit-fps: true
  human-skin: Business Man
  zoom: 0.5
  movement-decay: 0.8
  movement-force: 10
  min-speed: 7