display:
  borderless-fullscreen: false
  resolution:
    width: 1080
    height: 768
debug:
  world-name: collision_test.tmx
  limit-fps: true
  human-skin: Business Man
  zoom: 0.5
  movement-decay: 0.77
  movement-force: 200
  start-pos:
    x: 18
    y: 22